### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by punkpeye** [Sivan22/mcp-otzaria-server#1]
I'm trying to start this server so I can mark the associated [listing](https://glama.ai/mcp/servers/y5y2a19u1s) as tested.

### Current Behavior

This is my `Dockerfile`:

```Dockerfile
FROM python:3.10

RUN pip install uv

WORKDIR /app

RUN git clone https://github.com/Sivan22/mcp-otzaria-server .

RUN uv sync

CMD ["uv", "run", "jewish_library"]
```

When I run it, I get the following error:

```
2024-12-25 14:47:10,285 - jewish_library.tantivy_search_agent - ERROR - Failed to open Tantivy index: Failed to open the directory: 'DoesNotExist("/app/index")'
2024-12-25 14:47:10,285 - jewish_library - ERROR - Failed to initialize search agent: Failed to open the directory: 'DoesNotExist("/app/index")'
Traceback (most recent call last):
  File "/app/.venv/bin/jewish_library", line 5, in <module>
    from jewish_library import main
  File "/app/src/jewish_library/__init__.py", line 1, in <module>
    from . import server
  File "/app/src/jewish_library/server.py", line 27, in <module>
    search_agent = TantivySearchAgent(index_path)
  File "/app/src/jewish_library/tantivy_search_agent.py", line 18, in __init__
    self.index = Index.open(index_path)
ValueError: Failed to open the directory: 'DoesNotExist("/app/index")'

```

### Expected Behavior

The server should start correctly when using `uv run`.

### Suggested Improvement

Could you provide a complete example in the README showing how to start the server using uv run?

This would improve usability for developers and help automated systems like [Glama](https://glama.ai/mcp/servers) to test the server

**Comment by Sivan22** [comment]
You neeb first to get the index as described in the readme.md
download and extract the index from [here](https://drive.google.com/file/d/1lpbBCPimwcNfC0VZOlQueA4SHNGIp5_t/view?usp=drive_link)
I may add in the future some code for automatic download through gdown etc.
Feel free to create a pull request for that.
